mineral_catalog/urls.py
"""mineral_catalog URL configuration"""
from django.views.generic.base import RedirectView
from django.urls import path, re_path

from . import views

app_name = 'catalog'
urlpatterns = [
    path('', views.redirect_to_list),
    re_path(r'^list\/(?P<letter>[a-zA-Z])$', views.list_minerals_by_letter, name='list'),
    path('list/group/<group>', views.list_minerals_by_group, name='list_by_group'),
    path('list/group/', RedirectView.as_view(pattern_name='catalog:list', permanent=True)),
    path('list/', views.redirect_to_list),
    path('view/<slug:mineral_slug>/', views.detail_mineral, name='detail'),
    path('view/', views.redirect_to_list),
    path('search/', views.search, name='search'),
    path('search/color/', views.search_by_color, name='search_by_color'),
]

mineralz/urls.py
"""mineralz project URL configuration"""
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import RedirectView

favicon_view = RedirectView.as_view(url='/static/favicon.ico', permanent=True)

urlpatterns = [
    path('favicon.ico/', favicon_view),
    path('', include('mineral_catalog.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

mineral_catalog/models.py
"""mineral_catalog models"""
from django.db import models
from django.utils.text import slugify

MAX_LENGTH = 500


class Mineral(models.Model):
    """Model that describes a mineral in detail"""
    name = models.CharField(max_length=MAX_LENGTH)
    slug = models.SlugField(unique=True, max_length=MAX_LENGTH)
    image_filename = models.CharField(max_length=MAX_LENGTH)
    image_caption = models.CharField(blank=True, max_length=MAX_LENGTH)
    category = models.CharField(blank=True, max_length=MAX_LENGTH)
    formula = models.CharField(blank=True, max_length=MAX_LENGTH)
    strunz_classification = models.CharField(blank=True, max_length=MAX_LENGTH)
    crystal_system = models.CharField(blank=True, max_length=MAX_LENGTH)
    unit_cell = models.CharField(blank=True, max_length=MAX_LENGTH)
    color = models.CharField(blank=True, max_length=MAX_LENGTH)
    crystal_symmetry = models.CharField(blank=True, max_length=MAX_LENGTH)
    cleavage = models.CharField(blank=True, max_length=MAX_LENGTH)
    mohs_scale_hardness = models.CharField(blank=True, max_length=MAX_LENGTH)
    luster = models.CharField(blank=True, max_length=MAX_LENGTH)
    streak = models.CharField(blank=True, max_length=MAX_LENGTH)
    diaphaneity = models.CharField(blank=True, max_length=MAX_LENGTH)
    optical_properties = models.CharField(blank=True, max_length=MAX_LENGTH)
    refractive_index = models.CharField(blank=True, max_length=MAX_LENGTH)
    crystal_habit = models.CharField(blank=True, max_length=MAX_LENGTH)
    specific_gravity = models.CharField(blank=True, max_length=MAX_LENGTH)
    group = models.CharField(blank=True, max_length=MAX_LENGTH)

    class Meta:
        ordering = ['slug']

    def __str__(self):
        return self.name

    def _get_unique_slug(self):
        slug = slugify(self.name)
        unique_slug = slug
        num = 1
        while Mineral.objects.filter(slug=unique_slug).exists():
            unique_slug = '{}-{}'.format(slug, num)
            num += 1

        return unique_slug

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self._get_unique_slug()

        super().save(*args, **kwargs)

mineral_catalog/views.py
"""mineral_catalog views"""
from django.db.models import Q
from django.shortcuts import redirect, render

from .models import Mineral


def redirect_to_list(request):
    """Permanently redirect to the home list page"""
    return redirect('catalog:list', letter='a', permanent=True)


def list_minerals_by_letter(request, letter='a'):
    """List minerals starting with the provided letter (A if none)"""
    minerals = Mineral.objects.filter(name__istartswith=letter)

    return render(request, 'mineral_catalog/list.html', {'minerals': minerals})


def list_minerals_by_group(request, group):
    """List minerals by which group they belong to"""
    group = group.replace('_', ' ')
    minerals = Mineral.objects.filter(group__iexact=group)

    return render(request, 'mineral_catalog/list.html', {'minerals': minerals})


def detail_mineral(request, mineral_slug):
    """Show all the attributes of a particular mineral"""
    mineral = Mineral.objects.get(slug=mineral_slug)
    fields = (
        'category',
        'formula',
        'strunz_classification',
        'crystal_system',
        'unit_cell',
        'color',
        'crystal_symmetry',
        'cleavage',
        'mohs_scale_hardness',
        'luster',
        'streak',
        'diaphaneity',
        'optical_properties',
        'refractive_index',
        'crystal_habit',
        'specific_gravity',
        'group',
    )

    return render(request, 'mineral_catalog/detail.html', {'mineral': mineral, 'fields': fields})


def search(request):
    """Show all the minerals whose name contains the search query"""
    query = request.GET.get('query')
    minerals = Mineral.objects.filter(
        Q(name__istartswith=query)
        | Q(slug__istartswith=query)
        | Q(image_filename__istartswith=query)
        | Q(image_caption__istartswith=query)
        | Q(category__istartswith=query)
        | Q(formula__istartswith=query)
        | Q(strunz_classification__istartswith=query)
        | Q(crystal_system__istartswith=query)
        | Q(unit_cell__istartswith=query)
        | Q(color__istartswith=query)
        | Q(crystal_symmetry__istartswith=query)
        | Q(cleavage__istartswith=query)
        | Q(mohs_scale_hardness__istartswith=query)
        | Q(luster__istartswith=query)
        | Q(streak__istartswith=query)
        | Q(diaphaneity__istartswith=query)
        | Q(optical_properties__istartswith=query)
        | Q(refractive_index__istartswith=query)
        | Q(crystal_habit__istartswith=query)
        | Q(specific_gravity__istartswith=query)
        | Q(group__istartswith=query)
    )

    return render(request, 'mineral_catalog/list.html', {'minerals': minerals})


def search_by_color(request):
    """Show all minerals that match a query minerals' color field"""
    query = request.GET.get('query')
    minerals = Mineral.objects.filter(color__icontains=query)

    return render(request, 'mineral_catalog/list.html', {'minerals': minerals})

mineral_catalog/templates/mineral_catalog/base.html
{% load static %}

{% load concat %}
{% load getattr %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>
            {% block title %}Mineralz{% endblock %}
        </title>
        <meta name="description" content="Crazy catalog of Mineralz">
        <meta name="author" content="Kris Spenser">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="{% static 'favicon.ico' %}" rel="icon" type="image/x-icon">
        <link href="{% static 'css/global.css' %}" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,500" rel="stylesheet" type="text/css">
        <link href="https://fonts.googleapis.com/css?family=Cousine" rel="stylesheet" type="text/css">
    </head>
    <body>
        <div class="grid-100">
        <a href="{% url 'catalog:list' 'a' %}">
            <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
            </svg>
            <h1 class="logo__name text-centered">Mineralz</h1>
        </a>
        <p class="logo__text text-centered">Jesus Marie</p>
        </div>
        <section style="text-align:center;">
            <form action="{% url 'catalog:search' %}">
                <ul>
                    <li><input type="search" name="query"></li>
                    <li><button type="submit">Search</button></li>
                </ul>
            </form>
        </section>
        <section style="text-align:center;">
            <form action="{% url 'catalog:search_by_color' %}">
                <ul>
                    <li><input type="search" name="query"></li>
                    <li><button type="submit">Search by color</button></li>
                </ul>
            </form>
        </section>
        <section style="text-align:center;">
        {% for letter in 'abcdefghijklmnopqrstuvwxyz' %}
            {% with '/list/'|concat:letter as target_url %}
                {% if target_url == request.path %}
                <strong><a href="{% url 'catalog:list' letter %}">{{ letter }}</a></strong>
                {% else %}
                <a href="{% url 'catalog:list' letter %}">{{ letter }}</a>
                {% endif %}
            {% endwith %}
        {% endfor %}
        </section>
        <section style="text-align:center;">
        {% for key, value in groups.items %}
            {% with '/list/group/'|concat:key as target_url %}
                {% if target_url == request.path %}
                <strong><a href="{% url 'catalog:list_by_group' key %}">{{ value }}</a></strong>
                {% else %}
                <a href="{% url 'catalog:list_by_group' key %}">{{ value }}</a>
                {% endif %}
            {% endwith %}
        {% endfor %}
        </section>
        {% block content %}{% endblock %}
    </body>
</html>

mineral_catalog/templates/mineral_catalog/detail.html
{% extends 'mineral_catalog/base.html' %}
{% load static %}
{% load getattr %}

{% block title %}{{ mineral.name }} - {{ block.super }}{% endblock %}

{% block content %}
<div class="grid-100 mineral__container">
    <h1 class="mineral__name">{{ mineral.name }}</h1>
    <div class="mineral__image-bg">
        <img class="mineral__image" src="{% get_static_prefix %}images/{{ mineral.name }}.jpg">
        <p class="mineral__caption">{{ mineral.image_caption }}</p>
    </div>
    <div class="mineral__table-container">
        <table class="mineral__table">
            {% for field in fields %}
            <tr>
                {% if mineral|getattr:field %}
                    {% if field == 'formula' %}<td class="mineral__formula">{% else %}<td class="mineral__category">{% endif %}{{ field|title }}</td>
                    <td>{{ mineral|getattr:field|safe }}</td>
                {% endif %}
            </tr>
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

mineral_catalog/templates/mineral_catalog/list.html
{% extends 'mineral_catalog/base.html' %}

{% block content %}
    <div class="grid-100">
        <ul class="minerals__container">
            {% if not minerals %}
            <span style="text-align:center;">Sorry, no minerals here. Bummer!</span>
            {% else %}
                {% for mineral in minerals %}
                <li class="minerals__item">
                    <a class="minerals__anchor" href="{% url 'catalog:detail' mineral.slug %}">{{ mineral.name|capfirst }}</a>
                </li>
                {% endfor %}
            {% endif %}
        </ul>
    </div>
{% endblock %}